apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: component-sample
  namespace: default
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: application-sample
        appstudio.openshift.io/component: component-sample
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: component-sample-
      labels:
        appstudio.openshift.io/application: application-sample
        appstudio.openshift.io/component: component-sample
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: default
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio-qe/quarkus:next-$(tt.params.git-revision)
      - name: dockerfile
        value: src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
    status: {}
status: {}
